'use client';

/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { LogIn, Menu, Search, ShoppingBag, UserPlus, X } from 'lucide-react';
import { useCatalogProducts } from '@/hooks/useCatalogProducts';
import { useCartContext } from '@/context/CartContext';

type Product = { id: string; name: string; price: number; description?: string; image_url?: string; img?: string; category?: string; category_id?: string; category_name?: string; stock?: number | string; discount_percentage?: number; discountPercentage?: number; shopifyVariantId?: string; shopifyProductId?: string; shopifyHandle?: string };
const demo: Product[] = [{ id: 'demo-audio', name: 'Audífonos Bluetooth Pro', price: 24990, category: 'Audio', description: 'Audio inalámbrico para trabajo y movilidad.', image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=900&auto=format&fit=crop' }, { id: 'demo-power', name: 'Power Bank carga rápida', price: 19990, category: 'Energía', description: 'Energía portátil para tus equipos.', image_url: 'https://images.unsplash.com/photo-1609592806596-b43bada2f8e9?q=80&w=900&auto=format&fit=crop' }, { id: 'demo-smart', name: 'Kit Smart Home WiFi', price: 34990, category: 'Smart Home', description: 'Control inteligente para casa y negocio.', image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=900&auto=format&fit=crop' }];
function clp(n: number) { return new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(n || 0); }
function image(p: Product) { return p.image_url || p.img || '/omnifix-logo.svg'; }
function category(p: Product) { return p.category_name || p.category || p.category_id || 'Tecnología'; }
function pct(p: Product) { return p.discount_percentage ?? p.discountPercentage ?? 0; }
function final(p: Product) { const d = pct(p); return d > 0 ? Math.round(p.price * (1 - d / 100)) : p.price; }
function toCart(p: Product) { return { id: p.id, name: p.name, price: p.price, image_url: image(p), category_id: category(p), discount_percentage: pct(p), stock: typeof p.stock === 'number' ? p.stock : undefined, description: p.description, shopifyVariantId: p.shopifyVariantId, shopifyProductId: p.shopifyProductId, shopifyHandle: p.shopifyHandle } as never; }

export default function OmnifixStoreClient() {
  const { products } = useCatalogProducts();
  const { addToCart, openCart, totalItems } = useCartContext();
  const [q, setQ] = useState('');
  const [menu, setMenu] = useState(false);
  const list = useMemo<Product[]>(() => products.length ? products as Product[] : demo, [products]);
  const filtered = useMemo(() => list.filter((p) => `${p.name} ${p.description || ''} ${category(p)}`.toLowerCase().includes(q.toLowerCase().trim())), [list, q]);
  return <main className="min-h-screen bg-[#020617] pb-28 text-white"><div className="fixed inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(37,99,235,.28),transparent_34rem),radial-gradient(circle_at_90%_70%,rgba(34,211,238,.13),transparent_28rem)]" />
    <section className="relative mx-auto max-w-7xl px-4 py-6 md:px-8"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-12 w-12 overflow-hidden rounded-2xl bg-white"><img src="/omnifix-logo.svg" alt="Omnifix" className="h-full w-full object-cover" /></span><span><b className="block text-sm font-black uppercase tracking-[.22em]">OMNIFIX</b><small className="text-blue-200/65">Catálogo tech</small></span></Link><button onClick={openCart} className="relative grid h-12 w-12 place-items-center rounded-2xl bg-blue-400 text-black"><ShoppingBag className="h-5 w-5" />{totalItems > 0 && <span className="absolute -right-1 -top-1 rounded-full bg-cyan-200 px-1 text-[10px] font-black">{totalItems}</span>}</button></header>
    <div className="mt-8 rounded-[2rem] border border-blue-400/15 bg-white/[.06] p-6 backdrop-blur-2xl md:p-10"><p className="text-[10px] font-black uppercase tracking-[.30em] text-cyan-200/70">Tienda Omnifix</p><h1 className="mt-4 text-5xl font-black leading-[.9] tracking-[-.07em] md:text-7xl">Productos tech, sin vueltas.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-300">Compra productos, guarda tu cuenta y revisa tus pedidos. Shopify confirma pago, stock y checkout seguro.</p></div>
    <label className="sticky top-0 z-20 mt-6 flex h-14 items-center gap-3 rounded-2xl border border-blue-400/20 bg-slate-950/85 px-4 backdrop-blur-xl"><Search className="h-5 w-5 text-blue-200" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar producto..." className="w-full bg-transparent text-sm font-bold outline-none placeholder:text-white/40" /></label>
    <div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{filtered.map((p) => { const ok = p.shopifyVariantId?.startsWith('gid://shopify/ProductVariant/'); return <article key={p.id} className="overflow-hidden rounded-[1.8rem] border border-blue-400/15 bg-white/[.055] backdrop-blur-xl"><div className="h-56 bg-white/5"><img src={image(p)} alt={p.name} className="h-full w-full object-cover" /></div><div className="p-5"><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-300">{category(p)}</p><h2 className="mt-2 line-clamp-2 text-xl font-black">{p.name}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-400">{p.description || 'Producto seleccionado por Omnifix.'}</p><div className="mt-5 flex items-center justify-between gap-3"><b className="text-xl font-black text-blue-300">{clp(final(p))}</b><button onClick={() => addToCart(toCart(p))} disabled={Boolean(products.length) && !ok} className="rounded-full bg-blue-400 px-4 py-3 text-xs font-black uppercase text-black disabled:opacity-45">Agregar</button></div>{Boolean(products.length) && !ok && <p className="mt-3 text-xs text-amber-200/80">Producto sin variante Shopify válida.</p>}</div></article>; })}</div></section>
    {menu && <div className="fixed inset-x-3 bottom-[96px] z-[186] rounded-[1.7rem] border border-white/10 bg-slate-950/95 p-3 md:hidden"><div className="mb-3 flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.26em] text-blue-300">Menú rápido</p><button onClick={() => setMenu(false)} className="rounded-full bg-white/10 px-3 py-1 text-xs font-black"><X className="inline h-3 w-3" /> Cerrar</button></div><div className="grid gap-2"><Quick href="/auth" icon={LogIn} label="Iniciar sesión" sub="Entrar como cliente" /><Quick href="/auth?mode=register" icon={UserPlus} label="Registrarse" sub="Crear usuario de tienda" /><Quick href="/tienda/catalogo" icon={ShoppingBag} label="Catálogo completo" sub="Ver productos" /></div></div>}
    <div className="fixed inset-x-3 bottom-3 z-[185] rounded-[1.4rem] border border-white/10 bg-slate-950/92 p-2 backdrop-blur-2xl md:hidden"><div className="flex items-center gap-2"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-sky-200/75" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar producto..." className="h-12 w-full rounded-2xl bg-blue-400/15 px-10 text-sm font-black outline-none placeholder:text-white/55" /></label><button onClick={() => setMenu((v) => !v)} className="grid h-12 w-12 place-items-center rounded-2xl bg-white/[0.08]"><Menu className="h-5 w-5" /></button><button onClick={openCart} className="grid h-12 w-14 place-items-center rounded-2xl bg-blue-400 text-black"><ShoppingBag className="h-5 w-5" /></button></div></div></main>;
}
function Quick({ href, icon: Icon, label, sub }: { href: string; icon: typeof Menu; label: string; sub: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl bg-white/[0.07] p-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-black/35"><Icon className="h-5 w-5" /></span><span><b className="block text-sm">{label}</b><small className="opacity-60">{sub}</small></span></Link>; }
